CREATE TABLE Sheet1(Column_1 VARCHAR(10));
INSERT INTO Sheet1 (Column_1) VALUES 
('queries.sql'),
('-- createCREATE TABLE PetPet ( PetId INTEGER PRIMARY KEY, PetName VARCHAR NOT NULL, PetOwner VARCHAR NOT NULL, PetSpecies VARCHAR NOT NULL, PetGender VARCHAR NOT NULL, PetBirth DATE NOT NULL, PetDeath DATE NOT NULL);CREATE TABLE PetEvent ( PetEventId INTEGER PRIMARY KEY, PetName VARCHAR NOT NULL, EventDate DATE NOT NULL, EventType VARCHAR NOT NULL, Remark VARCHAR NOT NULL);'),
('created 30 minutes ago'),
(''),
('MySQL online editor'),
('Write, Run & Share MySQL queries online using OneCompiler's MySQL online editor and compiler for free. It's one of the robust, feature-rich online editor and compiler for MySQL. Getting started with the OneCompiler's MySQL editor is really simple and pretty fast. The editor shows sample boilerplate code when you choose language as 'MySQL' and start writing queries to learn and test online without worrying about tedious process of installation.'),
('About MySQL'),
('MySQL is a open-source, free and very popular relational database management system which is developed, distributed and supported by Oracle corporation.'),
('Key Features:'),
('Open-source relational database management systems.'),
('Reliable, very fast and easy to use database server.'),
('Works on client-server model.'),
('Highly Secure and Scalable'),
('High Performance'),
('High productivity as it uses stored procedures, triggers, views to write a highly productive code.'),
('Supports large databases efficiently.'),
('Supports many operating systems like Linux*,CentOS*, Solaris*,Ubuntu*,Windows*, MacOS*,FreeBSD* and others.'),
('Syntax help'),
('Commands'),
('1. CREATE'),
('Single-Line Comments:'),
('1. INSERT'),
('INSERT INTO table_name (column1, column2, column3, ...) VALUES (value1, value2, value3, ...);Note: Column names are optional.'),
('Example'),
('1. CREATE INDEX'),
('CREATE INDEX index_name on table_name(column_name);
To Create Unique index:'),
('2. DROP INDEX'),
('1. Create a View'),
('1. Create a Trigger'),
('1. Create a Stored Procedure'),
('1. INNER JOIN');